keep_notes/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from accounts.views import register_page,login_page,logout_page
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about/',views.AboutPage.as_view(),name='about'),
    path('register/',register_page,name='register'),
    path('login/',login_page,name='login'),
    path('logout/',logout_page,name='logout'),
    path('notes/',include (('notes.urls','notes'),namespace="note")),

]


urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path,include
from .views import show_notes,create_note

urlpatterns = [
        path("addnote/",create_note,name='addnote'),
        path("",show_notes,name='view'),
]

accounts/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed

# Create your models here.

class Notes(models.Model):
    label = models.CharField(max_length=200)
    body = models.TextField(max_length=20000)
    timestamp = models.DateTimeField(auto_now_add=True)
    # tags = models.ManyToManyField('Tag', related_name='notes', blank=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    active=models.BooleanField(default=True)


    def __str__(self):
        return str(self.id)

# def m2m_changed_note_count(sender,instance,*args,**kwargs):
#     if instance.products.all.count==0:
#         return


class Tag(models.Model):
    label = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

accounts/forms.py
from django import forms
from django.forms import ValidationError

class Login_form(forms.Form):
    username=forms.CharField(label="Username",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username'}))
    pwd=forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password'}))

class Register_Form(forms.Form):
    fname=forms.CharField(label="First name",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name'}))
    lname=forms.CharField(label="Last name",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter last Name'}))
    username=forms.CharField(label="Username",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username'}))
    email=forms.EmailField(label="Email",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Email'}))
    pwd=forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password'}))
    cpwd=forms.CharField(label="Password Confirmation",widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Re-enter Password'}))
    
    def clean(self):
        form_data=self.cleaned_data
        if form_data.get('pwd')==form_data.get('cpwd'):
            print(form_data)
            return form_data
        else:
            raise ValidationError("Password Dosent Match")

notes/forms.py
from django import forms
from notes.models import Notes

class NotesForm(forms.ModelForm):
    body=forms.CharField()
    label=forms.CharField()
    class Meta:
        model=Notes
        fields=['label','body']
    

accounts/views.py
from django.shortcuts import render,redirect
from .forms import Register_Form,Login_form
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate

# Create your views here.

def logout_page(request):
    logout(request)
    return redirect("home")


def login_page(request):
    login_pg=Login_form(request.POST or None )
    context={'form':login_pg}
    if login_pg.is_valid():
        un=login_pg.data.get('username')
        pw=login_pg.data.get('pwd')
        user=authenticate(username=un,password=pw)
        if user:
            print(user)
            login(request,user)
            return redirect('home')
    return render(request,'accounts/login1.html',context)



def register_page(request):
    register_form=Register_Form(request.POST or None)
    context={'form':register_form}
    if register_form.is_valid():
        fn=register_form.cleaned_data.get('fname')
        ln=register_form.cleaned_data.get('lname')
        un=register_form.cleaned_data.get('username')
        em=register_form.cleaned_data.get('email')
        pw=register_form.cleaned_data.get('pwd')
        cp=register_form.cleaned_data.get('cpwd')
        user=User.objects.create_user(first_name=fn,last_name=ln,username=un,email=em,password=pw)
        if user:
            context['msg']:'user Created'
        # else:
        #     register_form=Register_Form()
    return render(request,'accounts/register.html',context)

keep_notes/views.py
from django.views import generic

class HomePage(generic.TemplateView):
    template_name="main.html"

class AboutPage(generic.TemplateView):
    template_name="about.html"

notes/views.py
from django.shortcuts import render,get_object_or_404
from .models import Notes
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Notes
from .forms import NotesForm
from django.views.generic import ListView
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User

# Create your views here.


# class NotesListView(ListView):
#         template="notes/notes_list.html"
#         model=Notes

#         def get_context_data(self,*args,**kwargs):
#                 notes_list=Notes.objects.filter(owner=User)

def show_notes(request):
        note=Notes.objects.filter(owner=request.user)
        context={'object_list':note}
        return render(request,'notes/notes_list.html',context)






def create_note(request):
        form=NotesForm(request.POST or None)
        context={'form':form}
        if form.is_valid():
                lb=form.cleaned_data.get('label')
                bd=form.cleaned_data.get('body')
                t=Notes(owner=request.user,label=lb,body=bd)
                t.save()
                return redirect("home")
        else:
                form=NotesForm()
        return render(request,'notes/addnote1.html',context)

accounts/templates/accounts/login1.html
{% extends 'layout/layout.html' %}
{% block main %}
<div class="container form-box">
  <div class="text-center">
    <h2>Please Log In</h2>
  </div>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
<!-- <input type="submit" name="sign_in" value="Log in" class="btn btn-primary btn btn-lg btn-primary btn-block"
  id="submit-id-sign_in" /> -->
  <button><a href="{% url 'login' %}"> Log in </a></button>
</form>
</div>
<div class="form-message">
  <p>
    Don't have an account? <a href="{% url 'register' %}">Sign up</a>.
  </p>
</div>


{% endblock %}
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script> -->




<!-- <input type='hidden' name='csrfmiddlewaretoken' value='z2l8XVjHSiDLS9DWMZldAhv1acWVS4j786bIoOpwY3eggvp03NjkOpsOB9QGBy0F' /> 
    <div id="div_id_username" class="form-group">
        <label for="id_username" class="control-label  requiredField">
                Email address
        <span class="asteriskField">*</span>
            </label> 
        <div class="controls "> 
            <input autofocus="" class="textinput textInput form-control" id="id_username" maxlength="254" name="username" placeholder="Enter Email" type="email" required /> 
        </div> 
    </div> 
    <div id="div_id_password" class="form-group">
         <label for="id_password" class="control-label  requiredField">Password<span class="asteriskField">*</span> </label> 
         <div class="controls "> <input class="textinput textInput form-control" id="id_password" name="password" placeholder="Enter Password" type="password" required /> 
        </div> 
    </div>  -->
<!-- <a href="/password-reset/">Forgot Password?</a> <div class="form-group"> <div id="div_id_remember_me" class="checkbox"> <label for="id_remember_me" class="">  -->
<!-- <input class="checkboxinput" id="id_remember_me" name="remember_me" type="checkbox" />
                    Remember me
                </label>  -->

accounts/templates/accounts/register.html
{% extends 'layout/layout.html' %}
<!-- {% load crispy_forms_tags %} -->
{% block main %}
    <form method="POST">
        {% csrf_token %}
        <div class="container from-box col-6">
        <div class="text-center">
            <h2>Signing Up is Free</h2>
        </div>
            {% if msg %}
            {{ msg }}
            {% endif  %}
            {% crispy form %}
            <!-- {{ form.as_p }} -->
            <input type="submit"
            value="Sign up" class="btn-warning"/>
    </div>
    </form>
{% endblock %}

notes/templates/notes/addnote.html
<!-- 
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Toki - Keep a Note</title>
    
    <link rel="stylesheet" href="/static/toki/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/toki/bootstrap-theme.min.css" />
    
    
</head>
 -->
{% extends 'layout/layout.html' %}
{% block main %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/static/toki/js/bootstrap.min.js"></script>

<body role="document">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Toki</a>
                <a class="navbar-brand" href="/notes/">Notes</a>
                <a class="navbar-brand" href="/notes/addnote/">Add Note</a>
                <a class="navbar-brand" href="/notes/addtag/">Add Tag</a>
            </div>
            
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
              
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
            <img src="" alt="" />
            Mohit Punjabi
            <span class="caret"></span>
            </a>
            
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/users/me">Profile</a></li>
                    <li><a href="/logout/">Logout</a></li>
                  </ul>
                </li>
              
            
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        
    </div>

    
    
<link href="/static/pagedown/demo/browser/demo.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Editor.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/Markdown.Extra.js"></script>
<script type="text/javascript" src="/static/pagedown_init.js"></script>

    <link rel="stylesheet" href="/static/toki/theme.css" />
    <div class="container theme-showcase" role="main">
    
 



<link href="/static/pagedown/demo/browser/demo.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Editor.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/Markdown.Extra.js"></script>
<script type="text/javascript" src="/static/pagedown_init.js"></script>

<div class="jumbotron">
	<h1 align='center'>Create New Note!</h1>
</div>



<div class='col-md-12'>
	<form action="" method="post"><input type='hidden' name='csrfmiddlewaretoken' value='yO3UtvgM0bKSXcUP9GWqCylfTtINUioa4BeI3JCY9OkBOaGyKV4KEPSLLTK3U9Ir' />
  {% csrf_token %}
  {{ form.as_p }}
<!-- <div id="div_id_label" class="form-group"> <label for="id_label" class="control-label  requiredField">
                Label<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_label" maxlength="200" name="label" type="text" required /> </div> </div> <div id="div_id_body" class="form-group"> <label for="id_body" class="control-label  requiredField">
                Body<span class="asteriskField">*</span> </label> <div class="controls "> <div class="wmd-wrapper" id="id_body-wmd-wrapper"> <div class="wmd-panel"> <div id="id_body_wmd_button_bar"></div> <textarea class="pagedownwidget form-control wmd-input" cols="40" id="id_body" name="body" rows="10" required></textarea> </div> <p class="wmd-preview-title"><small>HTML Preview:</small></p> <div id="id_body_wmd_preview" class="wmd-panel wmd-preview"></div> </div> </div> </div> <div id="div_id_tags" class="form-group"> <label for="id_tags" class="control-label ">
                Tags
            </label> <div class="controls "> <select multiple="multiple" class="selectmultiple form-control" id="id_tags" name="tags">
<option value="14">python</option>
<option value="17">fish</option>
<option value="24">Machine learning</option>
</select> </div> </div> -->

	<input type='submit' value='Create New Note!' class='btn btn-primary btn-lg btn-block' />
	</form>
</div>



<script type='text/javascript'>
$('input[type="text"]').addClass('form-control');
$('textarea').addClass('form-control');
$('select').addClass('form-control');
</script>


    </div>

    <hr>
    
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; ShubhamNishad 2017</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="https://github.com/shubhamnishad97"><i class="fa fa-github"></i> GitHub</a> or
            <a href="https://twitter.com/shubhamnishad97"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" type="text/javascript"></script>
    
</body>
{% endblock %}
<!-- </html> -->

notes/templates/notes/addnote1.html
{% extends 'layout/layout.html' %}
{% block main %}
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
<input type="submit"   class="btn btn-primary btn btn-lg btn-primary btn-block"
  id="submit-id-sign_in" /> 

</form>
{% endblock %}

notes/templates/notes/notes_list.html
 {% extends 'layout/layout.html' %}
 {% block main %}
 {% include 'layout/header.html' %}
 <h2>Notes</h2>
 <ul class="list-group-item">
     {% for obj in object_list %}
         <li class="list-group-item">
             <h3><a>{{ obj.label }}</a></h3>
             <div><p>{{ obj.body }}</p></div>
             <a href="#">Delete </a>
         </li>
 
     {% empty %}
         <li>No Notes yet.</li>
     {% endfor %}
     <!-- {{object_list}} -->
 </ul>
 {% endblock %}
 

<!-- 

<
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Toki - Keep a Note</title>
    
    <link rel="stylesheet" href="/static/toki/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/toki/bootstrap-theme.min.css" />
    
    
</head>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/static/toki/js/bootstrap.min.js"></script>

<body role="document">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Toki</a>
                <a class="navbar-brand" href="/notes/">Notes</a>
                <a class="navbar-brand" href="/notes/addnote/">Add Note</a>
                <a class="navbar-brand" href="/notes/addtag/">Add Tag</a>
            </div>
            
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
              
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
            <img src="" alt="" />
            Mohit Punjabi
            <span class="caret"></span>
            </a>
            
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/users/me">Profile</a></li>
                    <li><a href="/logout/">Logout</a></li>
                  </ul>
                </li>
              
            
          </ul>
          </ul>
        </div>
        
    </div>

    
    
    
    <link rel="stylesheet" href="/static/toki/theme.css" />
    <div class="container theme-showcase" role="main">
    


<div class='col-md-9'>

    <div class='alert alert-warning' align='center'>
        <h3>No Notes Yet!</h3>
    </div>

</div>

<div class='col-md-3'>
    <h3 class="page-header" align='center'>Tags</h3>
    <ul class="list-group">
        
            
            <li class="list-group-item">
                <a href="/notes/addtag/?id=14">python</a>
            </li>
            
            <li class="list-group-item">
                <a href="/notes/addtag/?id=17">fish</a>
            </li>
            
            <li class="list-group-item">
                <a href="/notes/addtag/?id=24">Machine learning</a>
            </li>
            
        
    </ul>
</div>
    
    <script type="text/javascript">
      $(document).ready(function(){
        $('.content-markdown').each(function(){
            var content = $(this).text();
            var markedContent = marked(content);
            $(this).html(markedContent);
        })
        
      })
    </script>

    </div>

    <hr>
    
      Some social button for contact will do 
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; ShubhamNishad 2017</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="https://github.com/shubhamnishad97"><i class="fa fa-github"></i> GitHub</a> or
            <a href="https://twitter.com/shubhamnishad97"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" type="text/javascript"></script>
    
</body>
</html>  -->

templates/about.html
{% extends 'layout/layout.html' %}

<!-- <!DOCTYPE html>
<html lang="en">
    
    
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Shubham Nishad">
    <link rel="shortcut icon" href="/static/site/ico/favicon.ico"> -->

    <title>Toki
 :: About</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this site -->
    
    <!-- <link href="/static/site/css/main.css" rel="stylesheet"> -->
    

    <!-- Custom tags for the head tag -->
    

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  <!-- </head> -->

{% block main %}
<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Toki
</h1>
        <p class="lead">Keep a note. Keep hacking ideas.</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <h5><p>Toki is a simple note taking Django project. It was developed to act as a Hands-on and increase my experience with a MVC framework(MTV as in the case of Django).</p></h5>
    <h5><p>I was interested in Django from the first time I searched about and after a little investigation I choose Django as the base for this project.</p></h5>
    <br>
    <br>
    <ul class="list-group"><h2>Features of Toki - keep a Note</h2>
      <li class="list-group-item">customize notes using the markdown editor.You dont need to know markdown the editor will help you.</li>
      <li class="list-group-item">Save, Update, Delete notes</li>
      <li class="list-group-item">support for code blocks and highlighting</li>
      <li class="list-group-item">Fully responsive. use any device and always find the best layout.</li>
    </ul>
    <br>
    <br>
    <ul class="list-group"><h2>Things I like about Django.</h2>
      <li class="list-group-item">Lots and lots of quality packages</li>
      <li class="list-group-item">Full featured web framework</li>
      <li class="list-group-item">Great community support and excellent documentation</li>
       <li class="list-group-item">Really good ORM. It was really easy to work with DB.</li>
      <li class="list-group-item">You can very quickly make a functional web app when you want to test your ideas.</li>
    </ul>
    <br>
    <br>
    <ul class="list-group"><h2>Things I Learned</h2>
      <li class="list-group-item">Working with a MVC or you can say MTV.</li>
      <li class="list-group-item">By doing this project I can to know how Django works and what power does it has.</li>
      <li class="list-group-item">integrating differnt packages into a single project</li>
      <li class="list-group-item">Database operations on a RDBMS</li>
      <li class="list-group-item">hosting and configuring the project on pythonanwhere.com</li>
    </ul>
     <h4> <p>for more details about the project and the source, you can get it on github  <a href="https://github.com/shubhamnishad97/toki-keep-a-note">Link</a></p></h4>
     <img class="img-responsive" src="/static/toki-screenshots/desktop/notesIndex.PNG">
     <img class="img-responsive" src="/static/toki-screenshots/desktop/addNotes.PNG">
     <img class="img-responsive" src="/static/toki-screenshots/desktop/editOrDelete.PNG">
     <img class="img-responsive" src="/static/toki-screenshots/desktop/userProfile.PNG">
     <img class="img-responsive" src="/static/toki-screenshots/desktop/adminUserLayout.PNG">
     <h4> <p>for more info go to the github page.  <a href="https://github.com/shubhamnishad97/toki-keep-a-note">Link</a></p></h4>
	</div>
</div>


{% endblock %}

templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
           <p class="element"></p>
    {% if not user.is_authenticated %}      
    <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
    <button class="btn btn-primary" onclick="myFunction()">login without account</button>
    {% else %}
    <a class="btn btn-primary" href="{% url 'notes:index' %}">Notes</a>
    {% endif %}
    <div id="details" style="color: black;"></div>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h3>Use it everywhere</h3>
      <p>Your notes stay updated across all your devices. No buttons to press. It just works. </p>
      
    </div>
    <div class="col-lg-4">
      <h3>Stay organized</h3>
      <p>Find notes quickly with instant searching and simple tags. Share a list, post some instructions, or publish your thoughts. </p>
      
    </div>
    <div class="col-lg-4">
      <h3>Markdown Support</h3>
      <p>With Markdownn support, its easy to write articles/ notes with rich text formatting</p>
      
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script type="text/javascript">
  function myFunction() {
    $('#details').html("<span>username:fake@gmail.com</span><p>   </p><span>password:fake</span>");

}
</script>

<script src="{% static 'site/js/site.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.6/typed.min.js"></script>
     <script type="text/javascript">
        var typed3 = new Typed('.element', {
           strings: ["Keep a note","Keep hacking ideas","Keep dreaming"],
           typeSpeed: 100,
           backSpeed: 100,
           smartBackspace: true, // this is a default
           loop: true,
           
         });
    </script>
{% endblock scripts %}

templates/layout/css.html
<!-- <link href="bootstrap.min.css" rel="stylesheet"> -->
<!-- <link href='css/main.css'  rel="stylesheet"> -->
{% load static %}

<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
<link href="{% static 'css/css1.css' %}" rel="stylesheet">
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->